language: java
sudo: required
dist: trusty
group: edge

addons:
  apt:
    packages:
      - oracle-java9-installer
  sonarcloud:
    organization: "trellis-ldp"
    token:
      secure: "ih+uIEI+qLmSq6ueW09Hn3RKIlrxcyGN+Pm0kBPa8m7vaWjyq8MZ458FokCI/I62a2XH+Hq3h425uzLVCoyVMPSaknaNua1dD+cI4st3MiYKtcqXYVyPs22zyyBJw2I76omL6Uf/qgcNdqTqNyHwo5PC01fU3U97huwRISiG0N1PFr0IANAKI4bFfpIC5tSbNNaVEhJ669Ul809oKDbS93X5kFmtQUsFi8FuPlqUFx0Wy7/NRDaiJJOGhmZLSfwnxp7JO3IkQ49rmZBZqBbnkO70JNZwid3T1U6igjgaP2wiLEHJ4GpqXUSia+eUyDChCUZHiIF6G0oJzA1kc+OJvN3o7HZDg1y2u9cCY7VZMM1hoa0C4QXhLseU7QOmfmlPbBTDOLjKH0ZT23wMcq8k2oXpVDdWkUHBYArQkSiQrk6wgCArxFufLEfo2xE6ac2nQ5cr7E/SCwltLHTWyTMPLpbCrVQQFk9UJ8ZKS88BPSYqRjBMK+xz6fdZIcipOU4EcFNZrOWvYUXa9rv051r7Zvt4LPbxt9FAJ4WaUJm6Yd7R8U8YRh1B80mEGG1ixpFO4s1mTCauba9AqA2nXn0dt6ZiR75c2xCEaFu3/YP4f47Td88UzB52M2ubbLPLM1w+oI1pvEPl7NbPhyxb63ap6qx0xFZPHusAb617HdZTzMk="

matrix:
  include:
    # JDK 8
    - jdk: oraclejdk8
      env: JDK_RELEASE='JDK 1.8'

    # JDK 9
    - jdk: oraclejdk9
      env: JDK_RELEASE='JDK 9'

    # JDK 10
    - env: JDK_RELEASE='JDK 10 Early-Access'
      install: . ./src/install/install-jdk-10.sh

  allow_failures:
    - env: JDK_RELEASE='JDK 10 Early-Access'

after_success:
  - ./gradlew jacocoTestReport coveralls sonarqube
